services:
  scheduler-0-of-0:
    command: &id001
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1753506274-1579917437
      LM_SERVER_BASE_PORT: 30248
      NODE_GPU_TOTAL: '0'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /root/share_models/auto_openai/auto_openai:/app/auto_openai
    - /root/share_models/auto_openai/auto_openai_lm_images:/app/auto_openai_lm_images
  scheduler-1-of-1:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1753506274-1691425639
      LM_SERVER_BASE_PORT: 30256
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /root/share_models/auto_openai/auto_openai:/app/auto_openai
    - /root/share_models/auto_openai/auto_openai_lm_images:/app/auto_openai_lm_images
  scheduler-2-of-2:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1753506274-1682525294
      LM_SERVER_BASE_PORT: 30264
      NODE_GPU_TOTAL: '2'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /root/share_models/auto_openai/auto_openai:/app/auto_openai
    - /root/share_models/auto_openai/auto_openai_lm_images:/app/auto_openai_lm_images
  scheduler-3-of-3:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1753506274-1290563637
      LM_SERVER_BASE_PORT: 30272
      NODE_GPU_TOTAL: '3'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /root/share_models/auto_openai/auto_openai:/app/auto_openai
    - /root/share_models/auto_openai/auto_openai_lm_images:/app/auto_openai_lm_images
version: '3'
