services:
  scheduler-0-of-0:
    command: &id001
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1752565602-759246527
      LM_SERVER_BASE_PORT: 30248
      NODE_GPU_TOTAL: '0'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: &id002
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  scheduler-1-of-1:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1752565602-706113836
      LM_SERVER_BASE_PORT: 30256
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-2-of-2:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1752565602-613941425
      LM_SERVER_BASE_PORT: 30264
      NODE_GPU_TOTAL: '2'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-3-of-3:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1752565602-391847221
      LM_SERVER_BASE_PORT: 30272
      NODE_GPU_TOTAL: '3'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
version: '3'
