services:
  scheduler-0_1-of-0:
    command: &id001
    - /bin/sh
    - -c
    - if [ -d /root/share_models/auto_openai/ ]; then cp -rf /root/share_models/auto_openai/auto_openai
      /app/ && python3 -m auto_openai.scheduler; else python3 -m auto_openai.scheduler;
      fi
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1753761735-735287078
      LM_SERVER_BASE_PORT: 30296
      NODE_GPU_TOTAL: 0,1
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ../conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  scheduler-2_3-of-1:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      GPU_TYPE: EF-S60
      LABEL: lm-server-1753761735-1433713881
      LM_SERVER_BASE_PORT: 30304
      NODE_GPU_TOTAL: 2,3
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ../conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
version: '3'
