REDIS_CLIENT_CONFIG:
  address: 10.12.101.202:6379
  username:
  password:
  cluster: False

OSS_CLIENT_CONFIG:
  endpoint_url: http://oss-cnsq01.cdsgss.com
  aws_access_key_id: ef55cb62ff7511edb70f46ae5a5d3b50
  aws_secret_access_key: cb78ddb9646518e554799c0f5ff1a3bd
  bucket_name: maas-1
  region_name:

QUEUE_TIMEOUT: 600
INFER_TIMEOUT: 100
USERFULL_TIMES_PER_MODEL: 20
UNUSERFULL_TIMES_PER_MODEL: 10
DEFAULT_MODEL_CONFIG_max_tokens: 4096
NODE_GPU_TOTAL: "4,5"
MOCK: false

COMFYUI_INPUTS_DIR: "/tmp"
#
COMFYUI_MODEL_ROOT_PATH: /root/share_models/webui-models
#
MASKGCT_MODEL_ROOT_PATH: "/root/share_models/MaskGCT-models/"
#
VLLM_MODEL_ROOT_PATH: /root/share_models/LLM
#
FUNASR_MODEL_ROOT_PATH: "/root/share_models/funasr-models/"
#
EMBEDDING_MODEL_ROOT_PATH: "/root/share_models/Embedding-models/"
#
LLM_TRANSFORMER_MODEL_ROOT_PATH: "/root/share_models/LLM/"
#
WEBUI_MODEL_ROOT_PATH: "/root/share_models/webui-models"
#
RERANK_MODEL_ROOT_PATH: "/root/share_models/Rerank-models/"
# 
DIFFUSERS_MODEL_ROOT_PATH: "/root/share_models/webui-models/"
#
GPU_DEVICE_ENV_NAME: TOPS_VISIBLE_DEVICES
ONLY_SERVER_TYPES: [] # ["vllm"]
GPU_TYPE: EF-S60
AVAILABLE_MODELS: ["ALL"]
MODELS:
  # LLM_MODELS:
  - name: "Qwen2.5-72B-Instruct"
    server_type: vllm
    api_type: LLM
    model_max_tokens: 10240
    description: "Qwen2.5-72B-Instruct"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 4
  - name: "Qwen2.5-32B-Instruct-GPTQ-Int4"
    server_type: vllm
    api_type: LLM
    model_max_tokens: 32768
    description: "Qwen2.5-32B-Instruct-GPTQ-Int4"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    quantization: gptq
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1
  - name: "Qwen2.5-7B-Instruct"
    server_type: vllm
    api_type: LLM
    model_max_tokens: 32768
    description: "Qwen2.5-7B-Instruct"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 2
      EF-S60:
        need_gpu_count: 1
  - name: "Qwen2.5-Coder-7B-Instruct"
    server_type: vllm
    api_type: LLM
    model_max_tokens: 32768
    description: "Qwen2.5-Coder-7B-Instruct"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 2
      EF-S60:
        need_gpu_count: 1
  - name: "codegeex4-all-9b"
    server_type: vllm
    api_type: LLM
    model_max_tokens: 131072
    description: "codegeex4-all-9b"
    need_gpu_count: 1
    template: template_glm4.jinja
    stop: ["<|user|>", "<|assistant|>"]
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 2
      EF-S60:
        need_gpu_count: 1
  - name: "glm-4-9b-chat"
    server_type: vllm
    api_type: LLM
    model_max_tokens: 131072
    description: "glm-4-9b-chat"
    need_gpu_count: 1
    template: template_glm4.jinja
    stop: ["<|user|>", "<|assistant|>"]
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 2
      EF-S60:
        need_gpu_count: 1

  # VISION_MODELS:
  - name: "glm-4v-9b"
    server_type: llm-transformer-server
    api_type: VLLM
    model_max_tokens: 8192
    description: "glm-4v-9b"
    need_gpu_count: 1
    template: template_glm4.jinja
    stop: []
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1

  # SD_MODELS:
  - name: "sd1.5/majicmixRealistic_betterV6.safetensors"
    server_type: comfyui
    api_type: SolutionBaseGenerateImage
    need_gpu_count: 1
    description: "majicmixRealistic_betterV6"
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1

  # TTS_MODELS:
  # - name: "maskgct-tts-clone"
  #   server_type: maskgct
  #   api_type: TTS
  #   need_gpu_count: 1
  #   description: "maskgct-tts-clone"
  #   gpu_types:
  #     NV-A100:
  #       need_gpu_count: 1
  #     NV-4090:
  #       need_gpu_count: 1
  #     EF-S60:
  #       need_gpu_count: 1

  # ASR_MODELS:
  - name: "funasr"
    server_type: funasr
    api_type: ASR
    need_gpu_count: 1
    description: "asr"
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1
      CPU:
        need_gpu_count: 1

  # EMBEDDING_MODELS:
  - name: "bge-base-zh-v1.5"
    server_type: embedding
    api_type: Embedding
    need_gpu_count: 1
    description: "bge-base-zh-v1.5"
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1
      CPU:
        need_gpu_count: 1
  - name: "bge-m3"
    server_type: embedding
    api_type: Embedding
    need_gpu_count: 1
    description: "bge-m3"
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1
      CPU:
        need_gpu_count: 1

  # RERANK_MODELS:
  - name: "bge-reranker-base"
    server_type: rerank
    api_type: Rerank
    need_gpu_count: 1
    description: "bge-reranker-base"
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1
      CPU:
        need_gpu_count: 1
  - name: "bge-reranker-v2-m3"
    server_type: rerank
    api_type: Rerank
    need_gpu_count: 1
    description: "bge-reranker-v2-m3"
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1
      CPU:
        need_gpu_count: 1
  # VIDEO_MODELS:
  - name: "CogVideo/CogVideoX-5b"
    server_type: diffusers-video
    api_type: Video
    need_gpu_count: 1
    description: "CogVideo/CogVideoX-5b"
    gpu_types:
      NV-A100:
        need_gpu_count: 1
      NV-4090:
        need_gpu_count: 1
      EF-S60:
        need_gpu_count: 1
