REDIS_CLIENT_CONFIG:
  address: 192.168.31.164:16379
  username:
  password: admin123
  cluster: False

OSS_CLIENT_CONFIG:
  endpoint_url: https://boto3.cpolar.cn
  aws_access_key_id: admin
  aws_secret_access_key: admin123
  bucket_name: api-platform
  region_name:

#######################################################
QUEUE_TIMEOUT: 600
INFER_TIMEOUT: 600
USERFULL_TIMES_PER_MODEL: 20
UNUSERFULL_TIMES_PER_MODEL: 10
DEFAULT_MODEL_CONFIG_max_tokens: 4096
NODE_GPU_TOTAL: "6"
MOCK: false
GPU_TYPE: CPU
IMAGE_BASE_PATH: "registry.cn-shanghai.aliyuncs.com/zhph-server"
AVAILABLE_MODELS: ALL
#######################################################
CUSTOM_MODLES:
  - name: EnflameCoder-14B-Instruct:10k
    server_type: vllm
    api_type: LLM
    model_max_tokens: 10240
    description: "Topscc 算子生成模型"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types:
      EF-S60:
        need_gpu_count: 1