REDIS_CLIENT_CONFIG:
  address: 10.12.101.202:6379
  username:
  password:
  cluster: False

OSS_CLIENT_CONFIG:
  endpoint_url: https://boto3-oss.cpolar.cn
  aws_access_key_id: admin
  aws_secret_access_key: admin123
  bucket_name: api-platform
  region_name:
  
#######################################################
QUEUE_TIMEOUT: 600
INFER_TIMEOUT: 600
USERFULL_TIMES_PER_MODEL: 20
UNUSERFULL_TIMES_PER_MODEL: 10
DEFAULT_MODEL_CONFIG_max_tokens: 4096
NODE_GPU_TOTAL: "4"
MOCK: false
GPU_TYPE: EF-S60
IMAGE_BASE_PATH: "harbor.uat.enflame.cc/library/enflame.cn"
#######################################################
SYSTEM_MODELS:
  - Qwen2.5-72B-Instruct
  - Qwen2.5-32B-Instruct-GPTQ-Int4
  - Qwen2.5-7B-Instruct
  - codegeex4-all-9b
  - glm-4-9b-chat
  - Qwen2.5-Coder-32B-GPTQ-Int4
  - Qwen2.5-Coder-32B-GPTQ-Int4-4k
  - Qwen2.5-Coder-32B-Instruct-GPTQ-Int4
  - Qwen2.5-Coder-32B-Instruct-GPTQ-Int4-4k
  - Qwen2.5-Coder-7B
  - Qwen2.5-Coder-7B-Instruct
  - Qwen2.5-Coder-14B
  - Qwen2.5-Coder-14B-Instruct
  - deepseek-coder-6.7b-base
  - deepseek-coder-6.7b-instruct
  - DeepSeek-Coder-V2-Lite-Instruct
  - DeepSeek-Coder-V2-Lite-Base
  - DeepSeek-Coder-V2-Lite-Instruct-8k
  - DeepSeek-Coder-V2-Lite-Base-8k
  - glm-4v-9b
  - majicmixRealistic_v7.safetensors/majicmixRealistic_v7.safetensors
  - SD15MultiControlnetGenerateImage/majicmixRealistic_v7.safetensors/majicmixRealistic_v7.safetensors
  - funasr
  - maskgct-tts-clone
  - bge-base-zh-v1.5
  - bge-m3
  - bge-reranker-base
  - bge-reranker-v2-m3
  - CogVideo/CogVideoX-5b
CUSTOME_MODELS: [] 