REDIS_CLIENT_CONFIG:
  address: 10.12.101.202:6379
  username:
  password:
  cluster: False

OSS_CLIENT_CONFIG:
  endpoint_url: https://boto3.cpolar.cn
  aws_access_key_id: admin
  aws_secret_access_key: admin123
  bucket_name: api-platform
  region_name:

#######################################################
QUEUE_TIMEOUT: 600
INFER_TIMEOUT: 600
USERFULL_TIMES_PER_MODEL: 20
UNUSERFULL_TIMES_PER_MODEL: 10
DEFAULT_MODEL_CONFIG_max_tokens: 4096
NODE_GPU_TOTAL: "5,6"
MOCK: false
GPU_TYPE: EF-S60
IMAGE_BASE_PATH: "harbor.uat.enflame.cc/library/enflame.cn"
AVAILABLE_MODELS: DeepSeek-Coder-V2-Lite-Base:10k,ALL
#######################################################
CUSTOM_MODLES:
  - name: EnflameCoder-14B-Instruct:10k
    server_type: vllm
    api_type: LLM
    model_max_tokens: 10240
    description: "Topscc 算子生成模型"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types:
      EF-S60:
        need_gpu_count: 1

  - name: DeepSeek-R1满血版
    model_name: ep-20250219145028-w67f6
    server_type: http-llm
    api_key: 8071659a-e617-4622-b671-f4933d194304
    base_url: https://ark.cn-beijing.volces.com/api/v3
    api_type: LLM
    model_max_tokens: 10240
    description: "DeepSeek-R1满血版"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types:
      CPU:
        need_gpu_count: 1

  - name: DeepSeek-V3满血版
    model_name: ep-20250219150704-gmnw4
    server_type: http-llm
    api_key: 8071659a-e617-4622-b671-f4933d194304
    base_url: https://ark.cn-beijing.volces.com/api/v3
    api_type: LLM
    model_max_tokens: 10240
    description: "DeepSeek-V3满血版"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types:
      CPU:
        need_gpu_count: 1