services:
  scheduler-0-of-0:
    command: &id001
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1734922220-1492693472
      LM_SERVER_BASE_PORT: 30160
      NODE_GPU_TOTAL: '0'
    image: harbor.uat.enflame.cc/library/enflame.cn/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: &id002
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  scheduler-1-of-1:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1734922220-84694231
      LM_SERVER_BASE_PORT: 30168
      NODE_GPU_TOTAL: '1'
    image: harbor.uat.enflame.cc/library/enflame.cn/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-2-of-2:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1734922220-931464229
      LM_SERVER_BASE_PORT: 30176
      NODE_GPU_TOTAL: '2'
    image: harbor.uat.enflame.cc/library/enflame.cn/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
version: '3'
