version: "3"
services:
  redis:
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    command:
      - redis-server
  openai-api:
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.1-cuda12.2
    ports:
      - "9000:9000"
    command:
      - /bin/sh
      - -c
      - |
        python3 -m auto_openai.main --port=9000 --workers=10
    restart: always
    volumes:
      - ./conf:/app/conf
    depends_on:
      - redis
