services:
  scheduler-0:
    command: &id001
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            device_ids:
            - '0'
            driver: nvidia
    environment:
      GPU_DEVICE_ENV_NAME: CUDA_VISIBLE_DEVICES
      GPU_TYPE: NV-A100
      NODE_GPU_TOTAL: '0'
      NVIDIA_VISIBLE_DEVICES: '0'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.1-cuda12.2
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: &id002
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
  scheduler-1:
    command: *id001
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            device_ids:
            - '1'
            driver: nvidia
    environment:
      GPU_DEVICE_ENV_NAME: CUDA_VISIBLE_DEVICES
      GPU_TYPE: NV-A100
      NODE_GPU_TOTAL: '1'
      NVIDIA_VISIBLE_DEVICES: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.1-cuda12.2
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-2:
    command: *id001
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            device_ids:
            - '2'
            driver: nvidia
    environment:
      GPU_DEVICE_ENV_NAME: CUDA_VISIBLE_DEVICES
      GPU_TYPE: NV-A100
      NODE_GPU_TOTAL: '2'
      NVIDIA_VISIBLE_DEVICES: '2'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.1-cuda12.2
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-3:
    command: *id001
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
            device_ids:
            - '3'
            driver: nvidia
    environment:
      GPU_DEVICE_ENV_NAME: CUDA_VISIBLE_DEVICES
      GPU_TYPE: NV-A100
      NODE_GPU_TOTAL: '3'
      NVIDIA_VISIBLE_DEVICES: '3'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.1-cuda12.2
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
version: '3'
