services:
  scheduler-2-of-0-Qwen2.5-VL-7B-Instruct:
    command:
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: Qwen2.5-VL-7B-Instruct:32k
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1743478622-132158844
      LM_SERVER_BASE_PORT: 30320
      NODE_GPU_TOTAL: '2'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
version: '3'
