services:
  scheduler-0-of-0:
    command: &id001
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-69308915
      LM_SERVER_BASE_PORT: 30008
      NODE_GPU_TOTAL: '0'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: &id002
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  scheduler-1-of-1:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-44923835
      LM_SERVER_BASE_PORT: 30016
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-2-of-2:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-1071084078
      LM_SERVER_BASE_PORT: 30024
      NODE_GPU_TOTAL: '2'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-3-of-3:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-940916976
      LM_SERVER_BASE_PORT: 30032
      NODE_GPU_TOTAL: '3'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-4-of-4:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-524217929
      LM_SERVER_BASE_PORT: 30040
      NODE_GPU_TOTAL: '4'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-5-of-5:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-878880237
      LM_SERVER_BASE_PORT: 30048
      NODE_GPU_TOTAL: '5'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-6-of-6:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-695002832
      LM_SERVER_BASE_PORT: 30056
      NODE_GPU_TOTAL: '6'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-7-of-7:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-897815748
      LM_SERVER_BASE_PORT: 30064
      NODE_GPU_TOTAL: '7'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
version: '3'
