services:
  scheduler-1-of-0:
    command: &id001
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: bge-reranker-v2-m3
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1743473817-1011729524
      LM_SERVER_BASE_PORT: 30384
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: &id002
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  scheduler-1-of-1:
    command: *id001
    environment:
      AVAILABLE_MODELS: bge-reranker-v2-m3
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1743473817-1287347181
      LM_SERVER_BASE_PORT: 30392
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-1-of-2:
    command: *id001
    environment:
      AVAILABLE_MODELS: bge-reranker-v2-m3
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1743473817-310558280
      LM_SERVER_BASE_PORT: 30400
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-1-of-3:
    command: *id001
    environment:
      AVAILABLE_MODELS: bge-reranker-v2-m3
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1743473817-277188467
      LM_SERVER_BASE_PORT: 30408
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
version: '3'
