services:
  scheduler-1-of-0:
    command:
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: DeepSeek-R1-Distill-Qwen-14B:20k
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1742479104-41401533
      LM_SERVER_BASE_PORT: 30312
      NODE_GPU_TOTAL: '1'
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes:
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
version: '3'
