services:
  scheduler-0_1-of-0:
    command: &id001
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1748004096-450439298
      LM_SERVER_BASE_PORT: 30072
      NODE_GPU_TOTAL: 0,1
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: &id002
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  scheduler-2_3-of-1:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1748004096-1547149241
      LM_SERVER_BASE_PORT: 30080
      NODE_GPU_TOTAL: 2,3
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-4_5-of-2:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1748004096-554294596
      LM_SERVER_BASE_PORT: 30088
      NODE_GPU_TOTAL: 4,5
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
  scheduler-6_7-of-3:
    command: *id001
    environment:
      AVAILABLE_MODELS: ALL
      AVAILABLE_SERVER_TYPES: ALL
      LABEL: lm-server-1748004096-1390009774
      LM_SERVER_BASE_PORT: 30096
      NODE_GPU_TOTAL: 6,7
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:0.2
    network_mode: host
    privileged: true
    restart: always
    shm_size: 8gb
    volumes: *id002
version: '3'
