# up
# docker-compose -f scheduler-0-1-2-3-4-5-6-7-of-1-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-2-3-4-5-6-7-of-2-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-2-3-4-5-6-7-of-4-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-2-3-4-5-6-7-of-8-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-2-3-of-1-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-2-3-of-2-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-2-3-of-4-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-2-of-1-docker-compose.yml up -d
# docker-compose -f scheduler-0-1-of-1-docker-compose.yml up -d
# docker-compose -f scheduler-0-of-1-Qwen2.5-Coder-32B-Instruct-GPTQ-Int4-docker-compose.yml up -d
# docker-compose -f scheduler-0-of-1-Wan2.1-TextToVideo-docker-compose.yml up -d
# docker-compose -f scheduler-100-100-of-1-docker-compose.yml up -d
# docker-compose -f scheduler-1-2-of-1-anyone-docker-compose.yml up -d
# docker-compose -f scheduler-1-of-1-DeepSeek-R1-Distill-Qwen-14B-docker-compose.yml up -d
# docker-compose -f scheduler-2-of-1-Qwen2-VL-7B-Instruct-docker-compose.yml up -d
# docker-compose -f scheduler-3-3-3-3-of-1-bge-base-zh-v1.5-docker-compose.yml up -d
# docker-compose -f scheduler-3-3-3-3-of-1-bge-reranker-v2-m3-docker-compose.yml up -d
# docker-compose -f scheduler-3-3-3-3-of-1-docker-compose.yml up -d
# docker-compose -f scheduler-3-3-of-1-Kolors-docker-compose.yml up -d
# docker-compose -f scheduler-4-4-4-4-of-1-docker-compose.yml up -d
