FROM nvcr.io/nvidia/pytorch:23.12-py3


RUN apt update -y && apt install curl git ffmpeg -y && python3 -m pip install --upgrade pip==24.0

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip config set global.trusted-host pypi.tuna.tsinghua.edu.cn

WORKDIR /workspace

RUN pip install vllm==0.7.2
# RUN pip3.10 install torch==2.3.0 --force-reinstall

RUN pip3.10 install protobuf==3.20 fire
RUN pip3.10 uninstall pynvml -y
RUN pip3.10 install git+https://github.com/huggingface/transformers accelerate
RUN pip3.10 install opencv-python==4.10.0.84
RUN pip3.10 install opencv-fixer==0.2.5 && python -c "from opencv_fixer import AutoFix; AutoFix()"
RUN pip3.10 install git+https://github.com/huggingface/transformers.git@336dc69d63d56f232a183a3e7f52790429b871ef
COPY ./template /template

ENTRYPOINT []

WORKDIR /root/share_models/LLM/

CMD "sleep infinity"





