FROM nvcr.io/nvidia/pytorch:23.12-py3


RUN apt update -y && apt install curl git ffmpeg -y && python3 -m pip install --upgrade pip==24.0

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip config set global.trusted-host pypi.tuna.tsinghua.edu.cn

WORKDIR /workspace

RUN pip install vllm==0.6.5
# RUN pip3.10 install torch==2.3.0 --force-reinstall

RUN pip3.10 install protobuf==3.20 fire
RUN pip3.10 uninstall pynvml -y
RUN wget https://gitee.com/lijiacai/transformers/releases/download/v4.45.0/transformers-4.45.0.dev0-py3-none-any.whl && pip3.10 install transformers-4.45.0.dev0-py3-none-any.whl
COPY ./template /template

ENTRYPOINT []

WORKDIR /root/share_models/LLM/

CMD "sleep infinity"





