REDIS_CLIENT_CONFIG:
  address: 192.168.6.200:6379
  username:
  password:
  cluster: False

OSS_CLIENT_CONFIG:
  endpoint_url: https://boto3.cpolar.cn
  aws_access_key_id: n0AzSuY1wktLqpTYd2Si
  aws_secret_access_key: OTkVzpgM4cSxssa5xtaP5RSlXgK0yEjahdyGctX2
  bucket_name: api-platform
  region_name:

#######################################################
QUEUE_TIMEOUT: 600
INFER_TIMEOUT: 600
USERFULL_TIMES_PER_MODEL: 20
UNUSERFULL_TIMES_PER_MODEL: 10
DEFAULT_MODEL_CONFIG_max_tokens: 4096
NODE_GPU_TOTAL: "4"
MOCK: false
GPU_TYPE: NV-A100
IMAGE_BASE_PATH: "registry.cn-shanghai.aliyuncs.com/zhph-server"
#######################################################
CUSTOME_MODELS: [] 
SYSTEM_MODELS:
  - Qwen2.5-72B-Instruct
  - Qwen2.5-72B-Instruct:10k
  - Qwen2.5-32B-Instruct-GPTQ-Int4
  - Qwen2.5-32B-Instruct-GPTQ-Int4:32k
  - Qwen2.5-32B-Instruct-GPTQ-Int4:4k
  - Qwen2.5-7B-Instruct
  - Qwen2.5-7B-Instruct:32k
  - glm-4-9b-chat
  - glm-4-9b-chat:32k
  - glm-4-9b-chat:10k
  - Qwen2.5-Coder-32B-GPTQ-Int4
  - Qwen2.5-Coder-32B-GPTQ-Int4:32k
  - Qwen2.5-Coder-32B-GPTQ-Int4:4k
  - Qwen2.5-Coder-32B-Instruct-GPTQ-Int4
  - Qwen2.5-Coder-32B-Instruct-GPTQ-Int4:32k
  - Qwen2.5-Coder-32B-Instruct-GPTQ-Int4:4k
  - Qwen2.5-Coder-7B
  - Qwen2.5-Coder-7B:32k
  - Qwen2.5-Coder-7B-Instruct
  - Qwen2.5-Coder-7B-Instruct:32k
  - Qwen2.5-Coder-14B
  - Qwen2.5-Coder-14B:10k
  - Qwen2.5-Coder-14B-Instruct
  - Qwen2.5-Coder-14B-Instruct:10k
  - deepseek-coder-6.7b-base
  - deepseek-coder-6.7b-base:10k
  - deepseek-coder-6.7b-base:32k
  - deepseek-coder-6.7b-instruct
  - deepseek-coder-6.7b-instruct:10k
  - deepseek-coder-6.7b-instruct:32k
  - DeepSeek-Coder-V2-Lite-Instruct
  - DeepSeek-Coder-V2-Lite-Instruct:10k
  - DeepSeek-Coder-V2-Lite-Instruct:8k
  - DeepSeek-Coder-V2-Lite-Base
  - DeepSeek-Coder-V2-Lite-Base:10k
  - DeepSeek-Coder-V2-Lite-Base:8k
  # - codegeex4-all-9b
  # - codegeex4-all-9b:32k
  # - codegeex4-all-9b:10k
  - glm-4v-9b
  - bge-base-zh-v1.5
  - bge-m3
  - bge-reranker-base
  - bge-reranker-v2-m3
  - CogVideo/CogVideoX-5b
  # - majicmixRealistic_v7.safetensors/majicmixRealistic_v7.safetensors
  - SD15MultiControlnetGenerateImage/majicmixRealistic_v7.safetensors/majicmixRealistic_v7.safetensors
  # - funasr
  # - maskgct-tts-clone