REDIS_CLIENT_CONFIG:
  address: 192.168.6.200:6379
  username:
  password:
  cluster: False

OSS_CLIENT_CONFIG:
  endpoint_url: https://boto3.cpolar.cn
  aws_access_key_id: admin
  aws_secret_access_key: admin123
  bucket_name: api-platform
  region_name:

#######################################################
QUEUE_TIMEOUT: 600
INFER_TIMEOUT: 600
USERFULL_TIMES_PER_MODEL: 20
UNUSERFULL_TIMES_PER_MODEL: 10
DEFAULT_MODEL_CONFIG_max_tokens: 4096
NODE_GPU_TOTAL: "4"
MOCK: false
GPU_TYPE: NV-A100
IMAGE_BASE_PATH: "registry.cn-shanghai.aliyuncs.com/zhph-server"
#######################################################
CUSTOM_MODLES:
  - name: DeepSeek-R1满血版
    model_name: ep-20250219101116-8mrh2
    server_type: http-llm
    api_key: ddc48c07-623b-4898-8210-bf52fbf1ea78
    base_url: https://ark.cn-beijing.volces.com/api/v3
    api_type: LLM
    model_max_tokens: 10240
    description: "DeepSeek-R1满血版"
    need_gpu_count: 1
    template: template_qwen.jinja
    stop: ["<|im_start", "<|", "<|im_end|>", "<|endoftext|"]
    gpu_types: 
      CPU:
        need_gpu_count: 1