version: "3"
services:
  redis:
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - auto_openai_network
    command:
      - redis-server --requirepass admin123
    # volumes:
    #   - /data/volumes/redis:/data
  minio:
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/minio:RELEASE.2023-03-20T20-16-18Z
    restart: always
    networks:
      - auto_openai_network
    ports:
      - 19000:9000
      - 19001:9001
    environment:
      TZ: "Asia/Shanghai"
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin123"
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    command: server /data --console-address ":9000" --address ":9001"
