services:
  openai-api:
    command:
    - /bin/sh
    - -c
    - if [ -d /root/share_models/auto_openai/ ]; then cp -rf /root/share_models/auto_openai/auto_openai
      /workspace/auto_openai && python3 -m auto_openai.main --port=9000; else python3
      -m auto_openai.main --port=9000; fi
    image: registry.cn-shanghai.aliyuncs.com/zhph-server/auto_openai:shdx
    ports:
    - 9000:9000
    restart: always
    volumes:
    - ../conf/:/app/conf
    - /root/share_models/:/root/share_models/
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
version: '3'
