name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  build-lm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/auto_openai:0.2 

    - name: Build and push Docker images(LM)
      env:
        DEVICE: gpu
        IMAGE_REGISTRY: "${{ vars.DOCKERHUB_USERNAME }}"
      run: |
        services=(
          "comfyui"
          "diffusers-server"
          "embedding-server"
          "funasr-server"
          "llm-transformer-server"
          "maskgct"
          "rerank-server"
          "vllm"
          "vllm-glm"
          "vllm-qwen2-vl"
          "webui"
        )
        
        for service in "${services[@]}"; do
          echo "Building $service for $DEVICE..."
          docker build -t "$IMAGE_REGISTRY/$service:$DEVICE" -f "auto_openai_lm_images/Dockerfile.$service.$DEVICE" auto_openai_lm_images/
          docker push "$IMAGE_REGISTRY/$service:$DEVICE"
        done
