name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Debug All
      run: |
        echo "检查 Secrets:"
        echo "DOCKERHUB_USERNAME (secret) 是否设置: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
        echo "DOCKERHUB_TOKEN (secret) 是否设置: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
        
        echo "检查 Variables:"
        echo "DOCKERHUB_USERNAME (var): ${{ vars.DOCKERHUB_USERNAME }}"
        echo "DOCKER_USERNAME (var): ${{ vars.DOCKER_USERNAME }}"
