services:
  scheduler-4_5:
    command:
    - /bin/sh
    - -c
    - python3 -m auto_openai.scheduler
    environment:
      GPU_TYPE: EF-S60
      NODE_GPU_TOTAL: 4,5
    image: harbor.uat.enflame.cc/library/enflame.cn/auto_openai:0.1
    privileged: true
    restart: always
    shm_size: 16gb
    volumes:
    - ./conf/:/app/conf
    - /root/share_models/:/root/share_models/
version: '3'
